Let docs pass through with custom toolchains
Following #2116, custom toolchains started to fail `rustup doc`, since
they can't list components to check if `rust-docs` is installed.

    error: toolchain 'system' does not support components
    error: caused by: invalid toolchain name: 'system'

Now custom toolchains just skip that component check, and it's up to the
user to have installed the documentation in their own way.